const siteUrls = [
  `http://www.accruharrisorchard.com.au/`,
  `http://www.perriams.co.nz/`,
  `https://maddenpartners.com.au/`,
  `http://www.spurlingcannon.co.uk/`,
  `http://www.mba.net.nz/`,
  `http://havenadvisers.co.nz/`,
  `http://www.donaldreid.co.uk/`,
  `http://www.equation.co.nz/`,
  `http://www.mytwocents.nz/`,
  // `https://www.asmaccountants.com/`,
  // `http://www.accountingsolutionsvictoria.com.au/`,
  // `http://www.panoramaaccounting.com.au/`,
  // `http://www.finnandpartners.co.nz/`,
  // `https://caldwellpenn.com/services/accounting-software/`,
  // `https://www.donaldreid.co.uk/about/people/`,
  // `http://www.ouryclark.com/`,
  // `http://www.focuspartners.com.au/`,
  // `https://tgspartners.com.au/`,
  // `http://www.chestergrey.co.nz/`,
  // `http://www.wasley-chapman.co.uk/`,
  // `http://www.johnsonpartners.com.au/`,
  // `http://www.moorethompson.co.uk/cloud/`,
  // `http://www.dfkbkm.com.au/`,
  // `http://www.elsbyandco.co.uk/`,
  // `http://www.ypartners.com.au/`,
  // `http://www.bspadvisory.com.au/`,
  // "http://www.theadminangels.co.nz/",
  // "http://www.figuresmatter.com.au/",
  // "http://www.bennettsproactive.co.nz/",
  // "http://www.pangeapartners.com.au/",
  // "https://www.weareace.com/",
  // "http://www.grahampaul.com/",
  // "http://www.finleys.co.za/",
  // "http://www.cruxadvice.co.nz/",
  // "http://www.wisemanaccountants.com.au/",
  // "https://www.qaccountants.com/",
  // "http://www.approved-accounting.co.uk/",
  // "http://www.vaaccountants.com.au/",
  // "http://www.theaccountancypeople.co.uk/xero/",
  // "https://jsaaccounting.com.au/",
  // "http://www.dsburge.co.uk/",
  // "http://www.pkf.com.au/",
  // "http://www.pococktongtrass.co.nz/",
  // "https://accountantsondomain.co.nz/",
  // "http://www.pocknells.co.uk/",
  // "http://www.mgiparkinson.com.au/",
  // "http://www.ready1.com.au/",
  // "http://www.elevationtax.com/",
  // "http://www.dvlaccounting.com.au/",
  // "http://www.jsagroup.com.au/",
  // "https://www.argylepro.com.au/",
  // "http://www.osbornegroup.co.nz/",
  // "http://www.kinderpocock.co.uk/",
  // "http://www.outsourcedfinance.co.za/",
  // "http://www.future-cloud.co.uk/",
  // "https://thekalculators.com.au/",
  "http://www.premiertaxsolutions.co.uk/",
  "http://www.pdandf.com.au/",
  "http://www.maxaccountants.co.uk/",
  "http://www.ency.co.uk/",
  "http://www.champconsultants.co.uk/",
  "http://www.martletpartnership.com/",
  "http://www.orangeumbrella.co.uk/",
  "https://www.contactone.com.sg/",
  "http://www.accumen.com.au/",
  "https://xero.beaufort.sg/",
  "http://www.ttca.co.uk/",
  "http://www.rethinkaccounting.nz/",
  "http://www.abacus-bean.co.uk/",
  "http://www.ginerisltd.com/",
  "http://www.sasca.co.nz/",
  "https://norwichaccountancyservices.co.uk/",
  "http://www.eclipseaccounting.com.au/",
  "http://www.elementalcosec.com/",
  "http://www.praxisllp.com/",
  "http://www.plantandassociates.com.au/",
  "https://edmisonmehr.ca/",
  "http://www.thompsonelphick.co.uk/",
  "http://www.cardell.com.au/",
  "http://www.bfskonsult.co.za/",
  "http://keybusinessconsultants.co.uk/",
  "http://www.tulipaccounting.com/",
  "https://www.langtons.uk.com/",
  "http://www.kh.com.au/",
  "https://www.restaurantbookkeepers.com.au/",
  // `www.passassociates.co.uk`,
];

module.exports = Array.from(new Set(siteUrls));

